services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp-php
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - coolify

  db:
    image: mariadb:10.11
    container_name: wp-db
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - coolify

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: wp-nginx
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./modsec/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
      - ./modsec/crs-setup.conf:/etc/nginx/modsec/crs-setup.conf
    depends_on:
      - wordpress
    networks:
      - coolify

volumes:
  db_data:

networks:
  coolify:
    external: true
